name: sweet spring
favicon: null
layout_spectrum: 0.4897369819227606
typography_spectrum: 0.9039133535698056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.45436643809080124
  lightness: 0.37681841058656573
  saturation: 0.11380111472681165
  rhythmicContrast: 0.9185570741537958
purpose: []
